# Change these first
owner: Sakneen # Your GitHub organization or username, where this repository lives
repo: uptime-status # The name of this repository

sites:
  - name: Backend Production
    url: $BACKEND_PRODUCTION_URL
    icon: https://img.sakneen.com/logos-email/logo_rOc78V2s7.png
    method: GET
    maxResponseTime: 5000
    maxRedirects: 3
    headers:
      - "User-Agent: Sakneen-StatusMonitor/1.0"
    expectedStatusCodes:
      - 200
    __dangerous__insecure: false
  - name: Backend Development
    url: $BACKEND_DEVELOPMENT_URL
    icon: https://img.sakneen.com/logos-email/logo_rOc78V2s7.png
    method: GET
    maxResponseTime: 5000
    maxRedirects: 3
    headers:
      - "User-Agent: Sakneen-StatusMonitor/1.0"
    expectedStatusCodes:
      - 200
    __dangerous__insecure: false
  - name: SaaS Production
    url: $SAAS_PRODUCTION_URL
    icon: https://img.sakneen.com/logos-email/logo_rOc78V2s7.png
    method: GET
    maxResponseTime: 5000
    maxRedirects: 3
    headers:
      - "User-Agent: Sakneen-StatusMonitor/1.0"
    expectedStatusCodes:
      - 200
    __dangerous__insecure: false
  - name: SaaS Development
    url: $SAAS_DEVELOPMENT_URL
    icon: https://img.sakneen.com/logos-email/logo_rOc78V2s7.png
    method: GET
    maxResponseTime: 5000
    maxRedirects: 3
    headers:
      - "User-Agent: Sakneen-StatusMonitor/1.0"
    expectedStatusCodes:
      - 200
    __dangerous__insecure: false
  - name: Manage Production
    url: $MANAGE_PRODUCTION_URL
    icon: https://img.sakneen.com/logos-email/logo_rOc78V2s7.png
    method: GET
    maxResponseTime: 5000
    maxRedirects: 3
    headers:
      - "User-Agent: Sakneen-StatusMonitor/1.0"
    expectedStatusCodes:
      - 200
    __dangerous__insecure: false
  - name: Manage Development
    url: $MANAGE_DEVELOPMENT_URL
    icon: https://img.sakneen.com/logos-email/logo_rOc78V2s7.png
    method: GET
    maxResponseTime: 5000
    maxRedirects: 3
    headers:
      - "User-Agent: Sakneen-StatusMonitor/1.0"
    expectedStatusCodes:
      - 200
    __dangerous__insecure: false

status-website:
  # Professional domain configuration
  cname: status.sakneen.com
  # baseUrl: /uptime-status
  theme: auto # Options: light, dark, auto, night
  logoUrl: https://img.sakneen.com/logos-email/logo_rOc78V2s7.png
  favicon: https://img.sakneen.com/logos-email/logo_rOc78V2s7.png
  name: Sakneen Status
  introTitle: "System Status & Performance Monitor"
  introMessage: "Real-time monitoring of Sakneen's services and infrastructure. This page provides transparency into our system performance and any ongoing incidents."
  
  # Professional navigation
  navbar:
    - title: Status Dashboard
      href: /
    - title: Service History
      href: /history
    - title: Performance Metrics
      href: /history
    - title: Main Website
      href: https://www.sakneen.com
      target: _blank
  
  # Custom links for professional appearance
  links:
    - rel: stylesheet
      href: https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap
  
  # Professional styling
  customHeadHtml: |
    <style>
      /* Professional color scheme */
      :root {
        --color-primary: #0070f3;
        --color-success: #00c851;
        --color-warning: #ffbb33;
        --color-danger: #ff4444;
        --color-text: #1a1a1a;
        --color-text-secondary: #666666;
        --color-bg: #ffffff;
        --color-border: #e5e5e5;
      }
      
      /* Dark mode support */
      @media (prefers-color-scheme: dark) {
        :root {
          --color-text: #ffffff;
          --color-text-secondary: #cccccc;
          --color-bg: #1a1a1a;
          --color-border: #333333;
        }
      }
      
      /* Typography */
      body {
        font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
        line-height: 1.6;
        color: var(--color-text);
      }
      
      /* Header styling */
      .hero-title {
        color: var(--color-primary);
        font-weight: 600;
      }
      
      .hero-subtitle {
        color: var(--color-text-secondary);
        font-weight: 400;
      }
      
      /* Status indicators */
      .status-up {
        color: var(--color-success);
        font-weight: 500;
      }
      
      .status-down {
        color: var(--color-danger);
        font-weight: 500;
      }
      
      .status-degraded {
        color: var(--color-warning);
        font-weight: 500;
      }
      
      /* Cards and components */
      .response-time-chart {
        border-radius: 12px;
        box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
        transition: transform 0.2s ease;
      }
      
      .response-time-chart:hover {
        transform: translateY(-2px);
      }
      
      /* Status table enhancements */
      table {
        border-collapse: collapse;
        width: 100%;
        margin: 20px 0;
      }
      
      th, td {
        padding: 12px;
        text-align: left;
        border-bottom: 1px solid var(--color-border);
      }
      
      th {
        font-weight: 600;
        background-color: var(--color-bg);
      }
      
      /* Responsive design */
      @media (max-width: 768px) {
        .navbar {
          flex-direction: column;
          gap: 10px;
        }
        
        table {
          font-size: 14px;
        }
        
        th, td {
          padding: 8px;
        }
      }
      
      /* Animation for status changes */
      .status-indicator {
        transition: all 0.3s ease;
      }
      
      /* Footer styling */
      .footer {
        text-align: center;
        padding: 20px;
        color: var(--color-text-secondary);
        font-size: 14px;
      }
    </style>
    
    <!-- Analytics and monitoring -->
    <script>
      // Add your analytics code here if needed
      console.log('Sakneen Status Page Loaded');
    </script>
  
  # SEO and social media optimization
  metaTags:
    - name: description
      content: "Real-time status monitoring for Sakneen services including Backend APIs, SaaS Platform, and Management Portal. Check current system health and performance metrics."
    - name: keywords
      content: "Sakneen, status, uptime, monitoring, SaaS, backend, system health, performance, API status, service availability"
    - name: author
      content: "Sakneen"
    - name: robots
      content: "index, follow"
    - property: og:title
      content: "Sakneen System Status & Performance Monitor"
    - property: og:description
      content: "Real-time monitoring of Sakneen's services and infrastructure with transparent performance metrics."
    - property: og:image
      content: "https://img.sakneen.com/logos-email/logo_rOc78V2s7.png"
    - property: og:url
      content: "https://status.sakneen.com"
    - property: og:type
      content: "website"
    - name: twitter:card
      content: "summary_large_image"
    - name: twitter:title
      content: "Sakneen System Status"
    - name: twitter:description
      content: "Real-time monitoring of Sakneen's services and infrastructure"
    - name: twitter:image
      content: "https://img.sakneen.com/logos-email/logo_rOc78V2s7.png"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

# User agent for requests
userAgent: Sakneen-Uptime-Monitor/1.0

# Skip deschedule for better reliability
skipDeschedule: true

# Delay between monitoring requests (ms) to avoid rate limiting
delay: 2000

# Professional notifications configuration
notifications:
  - type: email
    smtpHost: smtp.gmail.com
    smtpPort: 587
    smtpUsername: $SMTP_USERNAME
    smtpPassword: $SMTP_PASSWORD
    emailFrom: "Sakneen Status <noreply@sakneen.com>"
    emailTo: 
      - milad@sakneen.com
    template: |
      🚨 **SERVICE ALERT** 🚨
      
      Service: $SITE_NAME
      Status: $STATUS
      Time: $TIMESTAMP
      Response: $RESPONSE_CODE in $RESPONSE_TIME ms
      
      $SITE_URL
      
      ---
      View details: https://status.sakneen.com/history/$SITE_SLUG
      
      Sakneen Status Monitor
    onlyOnChange: true
  
  # Slack notifications for real-time alerts
  - type: slack
    webhook: $SLACK_WEBHOOK_URL
    channel: "#alerts"
    username: "Sakneen Status Bot"
    icon_emoji: ":warning:"
    template: |
      🚨 *SERVICE ALERT* 🚨
      
      *Service:* $SITE_NAME
      *Status:* $STATUS
      *Time:* $TIMESTAMP
      *Response:* $RESPONSE_CODE in $RESPONSE_TIME ms
      *URL:* $SITE_URL
      
      ---
      📊 *View Details:* https://status.sakneen.com/history/$SITE_SLUG
      🔍 *Status Dashboard:* https://status.sakneen.com
      
      _Sakneen Status Monitor_
    onlyOnChange: true
    
  # Slack notifications for recovery (when services come back up)
  - type: slack
    webhook: $SLACK_WEBHOOK_URL
    channel: "#alerts"
    username: "Sakneen Status Bot"
    icon_emoji: ":white_check_mark:"
    template: |
      ✅ *SERVICE RECOVERED* ✅
      
      *Service:* $SITE_NAME
      *Status:* $STATUS
      *Recovery Time:* $TIMESTAMP
      *Response:* $RESPONSE_CODE in $RESPONSE_TIME ms
      *URL:* $SITE_URL
      
      ---
      📊 *View Details:* https://status.sakneen.com/history/$SITE_SLUG
      🎉 All systems operational!
      
      _Sakneen Status Monitor_
    onlyOnChange: true

# Issue assignment for incident management
assignees:
  - miladezzat

# i18n configuration for multilingual support
i18n:
  activeIncidents: "Active Incidents"
  allSystemsOperational: "All Systems Operational"
  incidentReport: "Incident Report for"
  activeIncidentSummary: "Opened $DATE with $POSTS posts"
  incidentTitle: "Incident Details"
  incidentDetails: "Incident Details"
  incidentFixed: "Fixed"
  incidentOngoing: "Ongoing"
  incidentOpenedAt: "Opened at"
  incidentClosedAt: "Closed at"
  incidentSubscribe: "Subscribe to updates"
  overall: "Overall"
  up: "Up"
  down: "Down"
  degraded: "Degraded"
